<?php

namespace App\Http\Controllers\User;


use Illuminate\Http\Request;
use App\Http\Controllers\Voyager\VoyagerBaseController;

class CategoryController extends VoyagerBaseController
{
   public function index(Request $request, $author = true )
   {
        return parent::index($request,$author) ; // TODO: Change the autogenerated stub

   }
}
