<?php

namespace App\Http\Controllers\Admin;

use App\Events\AddEditUser;
use App\Http\Controllers\Voyager\VoyagerBaseController;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends VoyagerBaseController
{
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {

        return parent::store($request); // TODO: Change the autogenerated stub
    }
}
